service: reporting-api

provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 512
 timeout: 10
 region: us-east-2
 lambdaHashingVersion: '20220128' 
package:
  exclude:
    - '!node_modules/.prisma/attendance/client/libquery_engine-*'
    - 'node_modules/.prisma/attendance/libquery_engine-rhel-*'
    - '!node_modules/.prisma/attendance/libquery_engine-*'
    - '!node_modules/.prisma/giving/client/libquery_engine-*'
    - 'node_modules/.prisma/giving/libquery_engine-rhel-*'
    - '!node_modules/.prisma/giving/libquery_engine-*'
    - '!node_modules/.prisma/membership/client/libquery_engine-*'
    - 'node_modules/.prisma/membership/libquery_engine-rhel-*'
    - '!node_modules/.prisma/membership/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /

plugins:
  - serverless-layers
  
custom:
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: "lcs-layers"
